# See https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions.

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.23.0, 12.20.0, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@vanoss-co-archive"

      - run: npm ci --no-optional
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm run lint --if-present
      - run: npm run build --if-present
      - run: CI=true npm test --if-present -- --coverage
